### ISSUE TITLE
Invalid HTML in index.html

### ISSUE THREAD

**Issue by ax6160sv-s** [Dsek-LTH/landing-page#40]
According to [w3's HTML checker](https://validator.w3.org/nu/) index.html contains some invalid HTML. 

These few errors shouldn't be hard to clear up.

**Comment by frednordell** [comment]
I think it would be better if this issue was more specific, a person that wants to solve this has to do the investigative work already done to find the issue and solution!

Some things to think about when raising an issue:

- Where in the code are the issues?
- Which, if any, other parts of the code are affected?
- Suggested fixes
- Can i fix this myself and create a pull-request?

Also, try to link issues to the project and or milestones so it can be tracked :D 

@emilwihlander Maybe we can create some issue-templates to aid this process? 🤔

**Comment by emilwihlander** [comment]
@frednordell Issue-templates would be really nice for both this repo and member-page. I can investigate it.

And as Fred said, post at least the output from the checker so that it is clear what needs to be fixed.
